### ISSUE TITLE
Allow multiple zip keys

### ISSUE THREAD

**Issue by malramsay64** [malramsay64/experi#22]
With the current implementation I am unable to have two zip operations at the same level. Taking the below code as an example

```yaml
variables:
  zip:
    var1: [1, 2, 3]
    var2: [2, 3, 4]
  zip:
    var3: [a, b]
    var4: [x, y]
```

With the two `zip` keys this is an impossible data structure.

A possible solution is to allow for a list like below.

```yaml
variables:
  zip:
    - var1: [1, 2, 3]
      var2: [2, 3, 4]

    - var3: [a, b]
      var4: [x, y]
```

Alternatively the previous approach I was using didn't have this issue, although that does mean breaking things again.

I do think that the current implementation does make things a lot clearer for most cases.
