### ISSUE TITLE
Support file creation in command

### ISSUE THREAD

**Issue by malramsay64** [malramsay64/experi#39]
Allow for the creation of a file using a simple interface, something like
```yaml
file:
  - name:
  - contents:
  - template:
```
which would allow for the specification of the file content either inline or alternatively using
a template file.
